experiment_name: expA_anti_compression
output_dir: H:/deepfake_data/outputs_duong_huy/qrtd/expA
seed: 42
epochs: 33
batch_size: 2
num_workers: 0
learning_rate: 0.0002
weight_decay: 0.0001
n_frames: 16
image_size: 300
model_name: efficientnet-b4
pretrained: true
anti_compression: true
contrastive_enabled: false
reliability_enabled: false
use_amp: true
frame_chunk_size: 1
grad_checkpoint: true
grad_ckpt_segments: 4
early_stopping_patience: 5
early_stopping_min_delta: 0.001
train_real:
  - D:/duong_huy_ct7/deepfake-data/train/original
train_fake:
  - D:/duong_huy_ct7/deepfake-data/train/DeepFakeDetection
  - D:/duong_huy_ct7/deepfake-data/train/Deepfakes
  - D:/duong_huy_ct7/deepfake-data/train/Face2Face
  - D:/duong_huy_ct7/deepfake-data/train/FaceShifter
  - D:/duong_huy_ct7/deepfake-data/train/FaceSwap
  - D:/duong_huy_ct7/deepfake-data/train/NeuralTextures
val_real:
  - D:/duong_huy_ct7/deepfake-data/val/original
val_fake:
  - D:/duong_huy_ct7/deepfake-data/val/DeepFakeDetection
  - D:/duong_huy_ct7/deepfake-data/val/Deepfakes
  - D:/duong_huy_ct7/deepfake-data/val/Face2Face
  - D:/duong_huy_ct7/deepfake-data/val/FaceShifter
  - D:/duong_huy_ct7/deepfake-data/val/FaceSwap
  - D:/duong_huy_ct7/deepfake-data/val/NeuralTextures
